Repository alexkidthunder/MI_engSoftware_fase4, pull requests merged in 2021-06, with the labels that each got.

#123 todas as funcionalidades das telas de listagem e prontuario finalizadas
  app/Http/Controllers/EnfChefeController.php
  app/Http/Controllers/HomeController.php
  resources/views/agendamentos.blade.php
  resources/views/editarPerfil.blade.php
  resources/views/listaPacientes.blade.php
  resources/views/meusAgendamentos.blade.php
  resources/views/prontuario.blade.php
  routes/web.php
Labels: good first issue, metas

#127 povoamento prontuários
  BD/insercao_dados.sql
Labels: metas

#130 Correção da tela de editar perfil
  resources/views/editarPerfil.blade.php
Labels: bug

#133 povoamento prontuários
  BD/insercao_dados.sql
Labels: metas

#134 Atualizacao tela de prontuario e backup
  resources/views/admin/atribuicao.blade.php
  resources/views/admin/backup.blade.php
  resources/views/admin/menu.blade.php
  resources/views/agendamentos.blade.php
  resources/views/agendamentosRealizados.blade.php
  resources/views/cadastroProntuario.blade.php
  resources/views/editarPerfil.blade.php
  resources/views/esqueciSenha.blade.php
  resources/views/layouts/navbar-adm.blade.php
Labels: bug, metas

#135 configuracao para tablet
  resources/views/admin/cadastroUsuario.blade.php
  resources/views/admin/menu.blade.php
  resources/views/admin/remocaoUsuario.blade.php
  resources/views/cadastroPaciente.blade.php
  resources/views/cadastroProntuario.blade.php
  resources/views/enfChefe/cadastroAgendamento.blade.php
  resources/views/enfChefe/cadastroMedicamento.blade.php
Labels: bug

#137 Povoamento agendamento
  BD/complete_cids.sql
  BD/hospital_universitario.sql
  BD/hospital_universitario19_04_21.sql
  BD/hospital_universitario25_04.sql
  BD/insercao_dados.sql
Labels: metas

#138 "Tela" de Download e seu CSS
  public/css/download-style.css
  resources/views/download/listagem_pdf.php
Labels: enhancement

#139 navbar responsiva
  public/css/login-style.css
  public/css/navbar-style.css
  public/css/style.css
  public/img/onda.png
  resources/views/admin/menu.blade.php
  resources/views/esqueciSenha.blade.php
  resources/views/layouts/navbar-adm.blade.php
  resources/views/layouts/navbar-menu.blade.php
  resources/views/layouts/navbar.blade.php
  resources/views/login.blade.php
  resources/views/menu.blade.php
Labels: metas

#140 Correção permissao_cargo
  BD/insercao_dados.sql
  Procfile
Labels: bug, metas

#141 Resoluções de bugs e função de dowlonad de listagens e backup incompl…
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/EnfChefeController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/VerificaLoginController.php
  composer.json
  composer.lock
  resources/views/admin/backup.blade.php
  resources/views/agendamentos.blade.php
  resources/views/agendamentosRealizados.blade.php
  resources/views/enfChefe/agendamentos.blade.php
  resources/views/listaPacientes.blade.php
  resources/views/meusAgendamentos.blade.php
  routes/web.php
Labels: bug, metas

#144 Ajuste BD
  BD/hospital_universitario.sql
  BD/hospital_universitario19_04_21.sql
Labels: metas

#145 Atualizações importantes
  app/Http/Controllers/HomeController.php
  composer.json
  composer.lock
  public/css/style.css
  public/js/agendamentos.js
  public/js/editarPerfil.js
  public/js/listaPaciente.js
  public/js/permissao.js
  public/js/scriptprontuario.js
  resources/views/admin/backup.blade.php
  resources/views/agendamentos.blade.php
  resources/views/agendamentosRealizados.blade.php
  resources/views/enfChefe/agendamentos.blade.php
  resources/views/historicoProntuario.blade.php
  resources/views/listaPacientes.blade.php
  resources/views/meusAgendamentos.blade.php
  resources/views/prontuario.blade.php
  routes/web.php
Labels: bug, enhancement, metas

#151 Atualização de login, botão de sexo do usuário
  public/css/login-style.css
  public/css/navbar-style.css
  public/css/style.css
  public/img/onda.png
  public/img/wave.png
  resources/views/admin/cadastroUsuario.blade.php
  resources/views/admin/permissao.blade.php
  resources/views/cadastroPaciente.blade.php
  resources/views/esqueciSenha.blade.php
  resources/views/layouts/navbar-adm.blade.php
  resources/views/listaPacientes.blade.php
  resources/views/login.blade.php
Labels: bug, metas

#153 Adição de mais medicamentos e ajustes
  .env
  .gitignore
  BD/hospital_universitario19_04_21.sql
  BD/insercao_dados.sql
Labels: metas

#156 Atualizações no Log / Js da navbar (para o sessionStorage)
  app/Http/Controllers/AdminController.php
  package-lock.json
  public/css/style.css
  public/js/log.js
  public/js/navbar.js
  resources/views/admin/log.blade.php
  resources/views/layouts/navbar-adm.blade.php
  resources/views/layouts/navbar-menu.blade.php
  resources/views/layouts/navbar.blade.php
Labels: enhancement, help wanted

#159 Reformulação das telas de listagem (Para download do PDF)
  .env-example
  public/css/download-style.css
  public/js/log.js
  resources/views/download/listagem_agendamento_pdf.blade.php
  resources/views/download/listagem_medicamento_pdf.blade.php
  resources/views/download/listagem_paciente_pdf.blade.php
  resources/views/download/listagem_pdf.php
  resources/views/download/listagem_responsaveis_pdf.blade.php
Labels: enhancement

#160 Relatório Gerencial
  app/Http/Controllers/AdminController.php
  composer.lock
  resources/views/admin/relatorioGerencial.blade.php
Labels: metas

#162 relatorio gerencial
  resources/views/admin/relatorioGerencial.blade.php
Labels: metas

#167 Preparação pra atualizar o servidor
  BD/complete_cids.sql
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/EnfChefeController.php
  app/Http/Controllers/db.php
  resources/views/admin/relatorioGerencial.blade.php
  routes/web.php
Labels: metas

#168 cadastro de plantonista
  public/css/style.css
  resources/views/enfChefe/cadastroPlantonista.blade.php
  resources/views/enfChefe/listagemPlantonistas.blade.php
Labels: bug, metas

#169 atualizando historico de prontuario
  resources/views/historicoProntuario.blade.php
Labels: bug

#173 Atualização BD
  BD/complete_cids.sql
  BD/hospital_universitario19_04_21.sql
  BD/insercao_dados.sql
Labels: metas

#177 Navbar mobile e scroll prontuario
  public/css/login-style.css
  public/css/navbar-style.css
  public/css/style.css
  public/js/navbar.js
  public/js/scriptprontuario.js
  resources/views/layouts/navbar-adm.blade.php
  resources/views/layouts/navbar.blade.php
  resources/views/prontuario.blade.php
Labels: bug, metas

#179 Telas de Download
  resources/views/download/listagem_gerencial_pdf.blade.php
  resources/views/download/listagem_historico_pdf.blade.php
Labels: enhancement

#180 Download da ultima listagem implementado
  app/Http/Controllers/HomeController.php
  resources/views/admin/log.blade.php
  resources/views/admin/relatorioGerencial.blade.php
Labels: metas

#186 Mensagens de notificação
  BD/hospita_universitario_backup_2021-06-14-09-45-18.sql
  composer.json
  composer.lock
  public/css/style.css
  public/js/notification.js
  resources/views/admin/cadastroUsuario.blade.php
  resources/views/enfChefe/cadastroAgendamento.blade.php
  resources/views/layouts/navbar-adm.blade.php
  resources/views/layouts/navbar-menu.blade.php
Labels: metas

#187 Navbar Atualizada
  public/js/navbar.js
  resources/views/layouts/navbar-adm.blade.php
  resources/views/layouts/navbar-menu.blade.php
  resources/views/layouts/navbar.blade.php
Labels: metas

#189 Erros de tipos de input e required
  resources/views/admin/cadastroUsuario.blade.php
  resources/views/cadastroProntuario.blade.php
  resources/views/enfChefe/cadastroAgendamento.blade.php
  resources/views/enfChefe/cadastroLeito.blade.php
  resources/views/enfChefe/cadastroMedicamento.blade.php
  resources/views/historicoProntuario.blade.php
Labels: bug, metas

#188 Notificação de agendamentos em todas as paginas e bug da atribuição…
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/HomeController.php
  composer.lock
  resources/views/admin/atribuicao.blade.php
  resources/views/admin/backup.blade.php
  resources/views/admin/cadastroUsuario.blade.php
  resources/views/admin/log.blade.php
  resources/views/admin/menu.blade.php
  resources/views/admin/permissao.blade.php
  resources/views/admin/relatorioGerencial.blade.php
  resources/views/admin/remocaoUsuario.blade.php
  resources/views/agendamentos.blade.php
  resources/views/agendamentosRealizados.blade.php
  resources/views/cadastroPaciente.blade.php
  resources/views/cadastroProntuario.blade.php
  resources/views/editarPerfil.blade.php
  resources/views/enfChefe/agendamentos.blade.php
  resources/views/enfChefe/cadastroAgendamento.blade.php
  resources/views/enfChefe/cadastroLeito.blade.php
  resources/views/enfChefe/cadastroMedicamento.blade.php
  resources/views/enfChefe/cadastroPlantonista.blade.php
  resources/views/enfChefe/listaResponsaveis.blade.php
  resources/views/enfChefe/listagemPlantonistas.blade.php
  resources/views/esqueciSenha.blade.php
  resources/views/historicoProntuario.blade.php
  resources/views/listaMedicamento.blade.php
  resources/views/listaPacientes.blade.php
  resources/views/menu.blade.php
  resources/views/meusAgendamentos.blade.php
  resources/views/prontuario.blade.php
  routes/web.php
Labels: bug, metas

#190 Erro de agendamento no prontuario corrigido
  app/Http/Controllers/HomeController.php
  resources/views/prontuario.blade.php
Labels: bug

#191 Prontuário e permissoes
  resources/views/admin/permissao.blade.php
  resources/views/prontuario.blade.php
Labels: bug

#193 Atualizações em prontuário (Agendamento, medicamento e CID)
  app/Http/Controllers/EnfChefeController.php
  resources/views/prontuario.blade.php
Labels: bug

#192 Correções no Banco de Dados
  BD/hospital_universitario.sql
  BD/hospital_universitario19_04_21.sql
  BD/insercao_dados.sql
  app/Console/Commands/AgendaBackup.php
Labels: metas

#195 Listagem de Plantonista (Tela de Download) e Tela de Download do Prontuário Criada
  public/js/navbar.js
  resources/views/download/listagem_plantonista_pdf.blade.php
  resources/views/download/listagem_prontuario_pdf.blade.php
Labels: metas

#197 required em botao de sexo do usuario
  resources/views/admin/cadastroUsuario.blade.php
  resources/views/cadastroPaciente.blade.php
  resources/views/editarPerfil.blade.php
Labels: bug

#198 Corrigido erro no Sexo do paciente, adicionado botão para editar dados
  public/js/scriptprontuario.js
  resources/views/prontuario.blade.php
Labels: metas

#200 Nome do hospital
  app/Http/Controllers/HomeController.php
  public/css/navbar-style.css
  resources/views/download/listagem_agendamento_pdf.blade.php
  resources/views/download/listagem_gerencial_pdf.blade.php
  resources/views/download/listagem_historico_pdf.blade.php
  resources/views/download/listagem_log_pdf.blade.php
  resources/views/download/listagem_medicamento_pdf.blade.php
  resources/views/download/listagem_paciente_pdf.blade.php
  resources/views/download/listagem_plantonista_pdf.blade.php
  resources/views/download/listagem_prontuario_pdf.blade.php
  resources/views/download/listagem_responsaveis_pdf.blade.php
  resources/views/layouts/navbar.blade.php
Labels: bug

#206 Segundo Nome na Navbar
  public/css/style.css
  public/js/navbar.js
  resources/views/admin/log.blade.php
  resources/views/layouts/navbar-adm.blade.php
  resources/views/layouts/navbar-menu.blade.php
  resources/views/layouts/navbar.blade.php
Labels: metas

#207 Agora a navbar mostra o Primeiro Nome e o Ultimo Sobrenome (Correção)
  public/js/navbar.js
Labels: enhancement

#213 Erros do prontuario concertados, login de adm funcional
  .env
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/HomeController.php
  resources/views/prontuario.blade.php
Labels: bug

#214 Retirado a contagem que ficava embaixo das CIDs (Prontuário)
  public/js/log.js
  resources/views/admin/log.blade.php
  resources/views/prontuario.blade.php
Labels: metas

#215 atualizando mensagens
  app/Http/Controllers/HomeController.php
Labels: bug

#217 Cadastro de novas cids no bd implementado, permissoes sumindo com opç…
  app/Http/Controllers/EnfChefeController.php
  app/Http/Controllers/HomeController.php
  composer.lock
  resources/views/layouts/navbar.blade.php
  resources/views/menu.blade.php
  resources/views/prontuario.blade.php
Labels: good first issue, metas

#221 designer mensagens de erro das telas de login
  public/css/login-style.css
  public/css/style.css
  resources/views/esqueciSenha.blade.php
  resources/views/login.blade.php
  resources/views/primeiroAcesso.blade.php
Labels: bug

#222 Modificação do nome na navbar e menu
  resources/views/layouts/navbar.blade.php
  resources/views/menu.blade.php
Labels: bug

#223 Mensagem de historico de prontuario
  app/Http/Controllers/HomeController.php
Labels: bug

#226 correcao de permissoes
  app/Http/Controllers/HomeController.php
  resources/views/admin/permissao.blade.php
  resources/views/layouts/navbar.blade.php
  resources/views/menu.blade.php
Labels: bug

#227 permissões concertadas
  app/Http/Controllers/HomeController.php
  composer.lock
Labels: bug
