Repository alexkidthunder/MI_engSoftware_fase4, pull requests merged in 2021-05, with the labels that each got.

#35 Tela de permissoes
  public/bootstrap/css/bootstrap.css
  resources/views/admin/permissao.blade.php
  resources/views/admin/remocaoUsuario.blade.php
Labels: metas

#36 Criado Scripts para as telas de Editar Perfil, Cadastro Usuário.
  app/Http/Controllers/HomeController.php
  public/js/backup.js
  public/js/cadastroUsuario.js
  public/js/editarPerfil.js
  resources/views/admin/backup.blade.php
  resources/views/admin/cadastroUsuario.blade.php
  resources/views/editarPerfil.blade.php
  resources/views/listaMedicamento.blade.php
  routes/web.php
Labels: metas

#38 Mensagens de erro e confimação
  app/Http/Controllers/HomeController.php
  public/bootstrap/css/bootstrap.css
  public/css/style.css
  public/img/favicon.png
  resources/views/admin/atribuicao.blade.php
  resources/views/admin/backup.blade.php
  resources/views/admin/cadastroUsuario.blade.php
  resources/views/admin/log.blade.php
  resources/views/admin/menu.blade.php
  resources/views/admin/permissao.blade.php
  resources/views/admin/remocaoUsuario.blade.php
  resources/views/agendamentos.blade.php
  resources/views/agendamentosRealizados.blade.php
  resources/views/cadastroPaciente.blade.php
  resources/views/editarPerfil.blade.php
  resources/views/enf/menu.blade.php
  resources/views/enfChefe/agendamentos.blade.php
  resources/views/enfChefe/cadastroAgendamento.blade.php
  resources/views/enfChefe/cadastroMedicamento.blade.php
  resources/views/enfChefe/cadastroPlantonista.blade.php
  resources/views/enfChefe/listaResponsaveis.blade.php
  resources/views/enfChefe/listagemPlantonistas.blade.php
  resources/views/enfChefe/menu.blade.php
  resources/views/enfChefe/prontuario.blade.php
  resources/views/esqueciSenha.blade.php
  resources/views/estagiario/menu.blade.php
  resources/views/layouts/navbar-adm.blade.php
  resources/views/layouts/navbar-menu.blade.php
  resources/views/layouts/navbar.blade.php
  resources/views/listaPacientes.blade.php
  resources/views/login.blade.php
  resources/views/mensagens.blade.php
  resources/views/meusAgendamentos.blade.php
  resources/views/primeiroAcesso.blade.php
  routes/web.php
Labels: metas

#40 Atribuição (Hiddens e JavaScript)
  public/js/cadastroAgendamento.js
  public/js/editarAtribuicao.js
  resources/views/admin/atribuicao.blade.php
  resources/views/enfChefe/cadastroAgendamento.blade.php
Labels: metas

#43 Alterações em Atribuição e Perfil
  public/css/style.css
  public/js/editarAtribuicao.js
  public/js/editarPerfil.js
  resources/views/admin/atribuicao.blade.php
  resources/views/editarPerfil.blade.php
Labels: metas

#45 Lista de medicamentos, backup, navbar e outras atualizações
  public/css/navbar-style.css
  public/css/style.css
  resources/views/admin/atribuicao.blade.php
  resources/views/admin/backup.blade.php
  resources/views/admin/cadastroUsuario.blade.php
  resources/views/admin/permissao.blade.php
  resources/views/cadastroPaciente.blade.php
  resources/views/editarPerfil.blade.php
  resources/views/enfChefe/cadastroAgendamento.blade.php
  resources/views/enfChefe/menu.blade.php
  resources/views/icons/license/license.html
  resources/views/icons/svg/admin-with-cogwheels.svg
  resources/views/icons/svg/calendar.svg
  resources/views/icons/svg/data-storage-device.svg
  resources/views/icons/svg/doctor.svg
  resources/views/icons/svg/download-to-storage-drive.svg
  resources/views/icons/svg/edit.svg
  resources/views/icons/svg/exit.svg
  resources/views/icons/svg/gear.svg
  resources/views/icons/svg/log-file-format.svg
  resources/views/icons/svg/personal-profile.svg
  resources/views/icons/svg/remove-user.svg
  resources/views/icons/svg/scrum.svg
  resources/views/layouts/navbar-adm.blade.php
  resources/views/layouts/navbar-menu.blade.php
  resources/views/layouts/navbar.blade.php
  resources/views/listaMedicamento.blade.php
Labels: bug

#48 Função de login atualizada e função de atribuição implementadaa
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/HomeController.php
  resources/views/admin/atribuicao.blade.php
  resources/views/admin/menu.blade.php
  routes/web.php
Labels: metas

#51 alterar senha
  public/css/style.css
  resources/views/editarPerfil.blade.php
  resources/views/esqueciSenha.blade.php
  routes/web.php
Labels: metas

#58 Padding da pagina de login e atualização do menu e navbar do enfermeiro chefe e enfermeiro
  public/css/login-style.css
  public/css/style.css
  resources/views/enf/menu.blade.php
  resources/views/enfChefe/menu.blade.php
  resources/views/layouts/navbar-enfChefe.blade.php
  resources/views/layouts/navbar.blade.php
Labels: metas

#57 Meta
  app/Http/Controllers/HomeController.php
  public/css/style.css
  public/js/agendamentos.js
  public/js/backup.js
  public/js/cadastroAgendamento.js
  public/js/cadastroUsuario.js
  public/js/editarAtribuicao.js
  public/js/editarPerfil.js
  public/js/historicoProntuario.js
  public/js/scriptprontuario.js
  resources/views/admin/backup.blade.php
  resources/views/admin/cadastroUsuario.blade.php
  resources/views/agendamentos.blade.php
  resources/views/editarPerfil.blade.php
  resources/views/enfChefe/cadastroAgendamento.blade.php
  resources/views/historicoProntuario.blade.php
  routes/web.php
Labels: metas

#59 atualizacao das mensagens de erro
  public/css/style.css
  resources/views/admin/atribuicao.blade.php
  resources/views/admin/backup.blade.php
  resources/views/admin/cadastroUsuario.blade.php
  resources/views/admin/log.blade.php
  resources/views/admin/menu.blade.php
  resources/views/admin/permissao.blade.php
  resources/views/admin/remocaoUsuario.blade.php
  resources/views/cadastroPaciente.blade.php
  resources/views/enf/menu.blade.php
  resources/views/enfChefe/agendamentos.blade.php
  resources/views/enfChefe/cadastroAgendamento.blade.php
  resources/views/enfChefe/cadastroLeito.blade.php
  resources/views/enfChefe/cadastroMedicamento.blade.php
  resources/views/enfChefe/cadastroPlantonista.blade.php
  resources/views/enfChefe/historicoEntradaSaida.blade.php
  resources/views/enfChefe/listaResponsaveis.blade.php
  resources/views/enfChefe/listagemPlantonistas.blade.php
  resources/views/enfChefe/menu.blade.php
  resources/views/enfChefe/prontuario.blade.php
  resources/views/login.blade.php
Labels: bug

#61 Envio de informações da permissão para view
  app/Http/Controllers/AdminController.php
  resources/views/admin/permissao.blade.php
Labels: bug, metas

#64 Função de permissão implementada, textos de atribuição implementada, …
  BD/insercao_dados.sql
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/HomeController.php
  resources/views/admin/atribuicao.blade.php
  resources/views/admin/permissao.blade.php
  resources/views/login.blade.php
Labels: bug, metas

#65 Atualização
  public/js/cadastroUsuario.js
  public/js/editarAtribuicao.js
  public/js/permissao.js
  resources/views/admin/cadastroUsuario.blade.php
  resources/views/admin/permissao.blade.php
  resources/views/cadastroPaciente.blade.php
  resources/views/editarPerfil.blade.php
Labels: documentation, enhancement

#66 Comentário de código e atualização de pasta
  app/Http/Controllers/EnfChefeController.php
  app/Http/Controllers/HomeController.php
  resources/views/agendamentos.blade.php
  resources/views/agendamentosRealizados.blade.php
  resources/views/cadastroPaciente.blade.php
  resources/views/cadastroProntuario.blade.php
  resources/views/enf/menu.blade.php
  resources/views/enfChefe/cadastroLeito.blade.php
  resources/views/enfChefe/historicoEntradaSaida.blade.php
  resources/views/enfChefe/menu.blade.php
  resources/views/esqueciSenha.blade.php
  resources/views/historicoProntuario.blade.php
  resources/views/layouts/navbar-enfChefe.blade.php
  resources/views/layouts/navbar.blade.php
  resources/views/listaMedicamento.blade.php
  resources/views/listaPacientes.blade.php
  resources/views/login.blade.php
  resources/views/mensagens.blade.php
  resources/views/meusAgendamentos.blade.php
  resources/views/primeiroAcesso.blade.php
  routes/web.php
Labels: documentation

#69 Sessões implementadas para todos os cargo
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/EnfChefeController.php
  app/Http/Controllers/EnfController.php
  app/Http/Controllers/EstagiarioController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/VerificaLoginController.php
  resources/views/admin/menu.blade.php
  resources/views/estagiario/menu.blade.php
  resources/views/layouts/navbar-adm.blade.php
  resources/views/layouts/navbar-enfChefe.blade.php
  resources/views/layouts/navbar-menu.blade.php
  resources/views/layouts/navbar.blade.php
  routes/web.php
Labels: metas

#72 Algumas das restrições de rotas por sessões implementadas
  app/Http/Controllers/EnfChefeController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/VerificaLoginController.php
  resources/views/layouts/navbar.blade.php
Labels: bug, metas

#73 Comentários e Correção em Remoção de Usuário
  public/js/agendamentos.js
  public/js/backup.js
  public/js/cadastroAgendamento.js
  public/js/cadastroUsuario.js
  public/js/editarAtribuicao.js
  public/js/editarPerfil.js
  public/js/historicoProntuario.js
  public/js/permissao.js
  resources/views/admin/atribuicao.blade.php
  resources/views/admin/backup.blade.php
  resources/views/admin/remocaoUsuario.blade.php
Labels: bug, documentation

#82 Remoção do código desnecessária e atualização da navbar
  resources/views/agendamentos.blade.php
  resources/views/agendamentosRealizados.blade.php
  resources/views/enfChefe/agendamentos.blade.php
  resources/views/enfChefe/listaResponsaveis.blade.php
  resources/views/historicoProntuario.blade.php
  resources/views/layouts/navbar.blade.php
  resources/views/listaMedicamento.blade.php
  resources/views/listaPacientes.blade.php
  resources/views/meusAgendamentos.blade.php
Labels: metas

#83 Responsividade e navbar
  app/Http/Controllers/AdminController.php
  public/css/navbar-style.css
  public/css/style.css
  resources/views/enf/menu.blade.php
  resources/views/enfChefe/menu.blade.php
  resources/views/estagiario/menu.blade.php
  resources/views/layouts/navbar-adm.blade.php
  resources/views/layouts/navbar-enfChefe.blade.php
  resources/views/layouts/navbar.blade.php
Labels: metas

#85 Remanejo da tela prontuario
  app/Http/Controllers/EnfChefeController.php
  app/Http/Controllers/HomeController.php
  public/css/navbar-style.css
  public/css/style.css
  resources/views/agendamentos.blade.php
  resources/views/agendamentosRealizados.blade.php
  resources/views/cadastroPaciente.blade.php
  resources/views/cadastroProntuario.blade.php
  resources/views/editarPerfil.blade.php
  resources/views/enfChefe/agendamentos.blade.php
  resources/views/enfChefe/cadastroAgendamento.blade.php
  resources/views/enfChefe/cadastroLeito.blade.php
  resources/views/enfChefe/cadastroMedicamento.blade.php
  resources/views/enfChefe/cadastroPlantonista.blade.php
  resources/views/enfChefe/listaResponsaveis.blade.php
  resources/views/enfChefe/listagemPlantonistas.blade.php
  resources/views/historicoProntuario.blade.php
  resources/views/layouts/navbar-enfChefe.blade.php
  resources/views/layouts/navbar.blade.php
  resources/views/listaMedicamento.blade.php
  resources/views/listaPacientes.blade.php
  resources/views/meusAgendamentos.blade.php
  resources/views/prontuario.blade.php
  routes/web.php
Labels: bug

#88 Responsividade - João
  public/css/style.css
  public/js/scriptprontuario.js
  resources/views/editarPerfil.blade.php
  resources/views/enfChefe/cadastroPlantonista.blade.php
  resources/views/enfChefe/listagemPlantonistas.blade.php
  resources/views/listaMedicamento.blade.php
Labels: enhancement, metas

#89 Responsividade de containers e box
  public/css/style.css
  resources/views/login.blade.php
Labels: metas

#90 Agrupamento de permissoes
  app/Http/Controllers/EnfChefeController.php
  public/js/permissao.js
  resources/views/admin/permissao.blade.php
  resources/views/menu.blade.php
Labels: metas

#91 menu unico para enf, enfChefe e estagiario
  app/Http/Controllers/EnfChefeController.php
  app/Http/Controllers/EnfController.php
  app/Http/Controllers/EstagiarioController.php
  app/Http/Controllers/HomeController.php
  resources/views/editarPerfil.blade.php
  resources/views/enf/menu.blade.php
  resources/views/enfChefe/menu.blade.php
  resources/views/estagiario/menu.blade.php
  resources/views/layouts/navbar-adm.blade.php
  resources/views/layouts/navbar.blade.php
  resources/views/menu.blade.php
  routes/web.php
Labels: metas

#94 Responsividade de todas as telas de listagem
  public/bootstrap/css/bootstrap-grid.css
  public/bootstrap/css/bootstrap.css
  public/css/style.css
  resources/views/admin/atribuicao.blade.php
  resources/views/admin/permissao.blade.php
  resources/views/admin/remocaoUsuario.blade.php
  resources/views/agendamentos.blade.php
  resources/views/agendamentosRealizados.blade.php
  resources/views/cadastroProntuario.blade.php
  resources/views/enfChefe/agendamentos.blade.php
  resources/views/enfChefe/cadastroAgendamento.blade.php
  resources/views/enfChefe/listaResponsaveis.blade.php
  resources/views/enfChefe/listagemPlantonistas.blade.php
  resources/views/historicoProntuario.blade.php
  resources/views/listaMedicamento.blade.php
  resources/views/listaPacientes.blade.php
  resources/views/meusAgendamentos.blade.php
Labels: metas

#96 Metas não relacionadas ao responsivo
  public/css/style.css
  public/js/permissao.js
  resources/views/admin/permissao.blade.php
  resources/views/enfChefe/cadastroAgendamento.blade.php
Labels: enhancement, metas

#98 Editar perfil e listar pacientes
  BD/insercao_dados.sql
  app/Http/Controllers/EnfChefeController.php
  app/Http/Controllers/HomeController.php
  composer.lock
  resources/views/admin/permissao.blade.php
  resources/views/editarPerfil.blade.php
  resources/views/enfChefe/agendamentos.blade.php
  resources/views/enfChefe/listagemPlantonistas.blade.php
  resources/views/listaMedicamento.blade.php
  resources/views/listaPacientes.blade.php
  routes/web.php
Labels: metas

#99 Atualizações em Permissões e em seu Javascript
  public/js/permissao.js
  resources/views/admin/permissao.blade.php
Labels: bug

#103 Botão de download e correção da página de perfil
  public/css/login-style.css
  public/css/style.css
  resources/views/admin/log.blade.php
  resources/views/admin/permissao.blade.php
  resources/views/editarPerfil.blade.php
  resources/views/enfChefe/agendamentos.blade.php
  resources/views/enfChefe/listaResponsaveis.blade.php
  resources/views/enfChefe/listagemPlantonistas.blade.php
  resources/views/esqueciSenha.blade.php
  resources/views/historicoProntuario.blade.php
  resources/views/listaMedicamento.blade.php
  resources/views/listaPacientes.blade.php
  resources/views/primeiroAcesso.blade.php
  resources/views/prontuario.blade.php
Labels: bug, metas

#107 responsividade do login e das telas de senha
  public/css/login-style.css
  public/img/doctors.png
  public/img/wave.png
  resources/views/esqueciSenha.blade.php
  resources/views/login.blade.php
  resources/views/primeiroAcesso.blade.php
Labels: metas

#109 Bugs de redirecionamento para login, endereço do logout aparecendo co…
  app/Http/Controllers/EnfChefeController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/VerificaLoginController.php
  composer.lock
Labels: bug, metas

#113 Geração automática das listagens e redirecionamento concertados
  app/Http/Controllers/EnfChefeController.php
  app/Http/Controllers/HomeController.php
  resources/views/agendamentos.blade.php
  resources/views/agendamentosRealizados.blade.php
  resources/views/enfChefe/agendamentos.blade.php
  resources/views/enfChefe/listaResponsaveis.blade.php
  resources/views/enfChefe/listagemPlantonistas.blade.php
  resources/views/listaMedicamento.blade.php
  resources/views/listaPacientes.blade.php
  resources/views/meusAgendamentos.blade.php
Labels: bug

#114 Responsividade das telas do ADM e do Prontuário
  public/css/style.css
  public/js/atribuicao.js
  public/js/removerUsuario.js
  resources/views/admin/atribuicao.blade.php
  resources/views/admin/backup.blade.php
  resources/views/admin/cadastroUsuario.blade.php
  resources/views/admin/log.blade.php
  resources/views/admin/remocaoUsuario.blade.php
  resources/views/editarPerfil.blade.php
  resources/views/enfChefe/cadastroPlantonista.blade.php
  resources/views/listaMedicamento.blade.php
  resources/views/prontuario.blade.php
Labels: enhancement, metas

#117 Historico de prontuario, alteração de senha no editar perfil, mensage…
  app/Http/Controllers/EnfChefeController.php
  app/Http/Controllers/HomeController.php
  resources/views/agendamentos.blade.php
  resources/views/agendamentosRealizados.blade.php
  resources/views/editarPerfil.blade.php
  resources/views/enfChefe/agendamentos.blade.php
  resources/views/enfChefe/listaResponsaveis.blade.php
  resources/views/historicoProntuario.blade.php
  resources/views/listaPacientes.blade.php
  resources/views/meusAgendamentos.blade.php
  resources/views/prontuario.blade.php
  routes/web.php
Labels: bug, metas
